name: Check for tests

on: [pull_request, workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit-tests
        run: npm run test-ci

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-results
          path: test-report.html
          retention-days: 30

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Browser
        run: npx playwright install

      - name: Download xvfb
        run: |
          sudo apt update
          sudo apt-get install xvfb -y

      - name: Run e2e tests
        run: xvfb-run npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-results
          path: playwright-report/
          retention-days: 30
